### ISSUE TITLE
Optimization of color() function

### ISSUE THREAD

**Issue by Oleg-N-Cher** [theflynn49/fsudoku#2]
```
void color(int col, int bkcol)
{
  char *c="\x11\x01\x11\x01" ;
  c[1] = (char)col ;
  c[3] = (char)bkcol ;
  //printf("\x11%c\x11%c",  (unsigned char)col, (unsigned char)bkcol) ;
  rst18l(c, 4) ;
}
```

As it turns out, both background and foreground colors can be set in one call =>

```
void color(int col, int bkcol)
{
  char *c="\x11\x01" ;
  c[1] = (char)(bkcol | 0x80 + col);
  rst18l(c, 2) ;
}
```

**Comment by theflynn49** [comment]
Hello... thank you for your interest.

I don't see how this would work : "char" is a 8-bits type. Your proposal for computing the parameter byte c[1] =  (char)(bkcol | 0x80 + col); will always result in a byte with the bit 0x80 set, so this command will (in my opinion) only set the background color with a mix of the two input parameters. 

Could you explain to me what I missed ?
Rgds
jF

**Comment by theflynn49** [comment]
Another way to look at this  : 
colors are in the range [0x00..0x1F] i.e. 5-bits values. There is no way to encode two of them in a single byte.
jF

**Comment by Oleg-N-Cher** [comment]
Well, I noticed that if you send code 17 (0x11) + color's code to VDP, the foreground color is set. If you add 128 (0x80) to the color, it will be the same color but the background color. Then I noticed that we can add both colors together, so you can set both background and foreground in one call.

Did you check the code?

**Comment by Oleg-N-Cher** [comment]
Or maybe you're right, but my code should work for 16-color modes...

**Comment by Oleg-N-Cher** [comment]
Yes, I apologize for my comment, you are correct. One call, one color.

**Comment by theflynn49** [comment]
Lol :D no problem. These fun machines are specially made for this purpose, exploring, hacking and trying things, so you are in the right spirit !
